use sepolicy::CilSourcePolicy;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn repo_path(path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(path)
}

struct TempPath {
    path: PathBuf,
}

impl TempPath {
    fn new(extension: &str) -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time went backwards")
            .as_nanos();

        let path = std::env::temp_dir().join(format!(
            "sepolicy_inject_rs_{}_{}.{}",
            std::process::id(),
            nanos,
            extension
        ));

        Self { path }
    }

    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TempPath {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.path);
    }
}

#[test]
fn test_patch_cil_source_with_simple_te_file() {
    let base_cil = fixture_path("extract_label.cil");
    let te_file = TempPath::new("te");
    let out_file = TempPath::new("cil");

    fs::write(
        te_file.path(),
        r#"
type test_domain, domain;
type test_exec, exec_type, file_type;
attribute test_attr;
expandattribute test_attr false;
typeattribute test_domain test_attr;
allow test_domain test_exec:file { read open };
type_transition init test_exec:process test_domain;
permissive test_domain;
"#,
    )
    .unwrap_or_else(|e| {
        panic!(
            "failed to write temporary TE file {}: {}",
            te_file.path().display(),
            e
        )
    });

    let mut policy = CilSourcePolicy::from_file(&base_cil).unwrap_or_else(|e| {
        panic!(
            "failed to load base CIL fixture {}: {}",
            base_cil.display(),
            e
        )
    });

    policy
        .load_rules_from_file(te_file.path(), std::iter::empty::<&Path>())
        .unwrap_or_else(|e| {
            panic!(
                "failed to render CIL patch from {}: {}",
                te_file.path().display(),
                e
            )
        });

    policy.write(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to write patched CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    let rendered = fs::read_to_string(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to read rendered CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    assert!(
        rendered.contains("(type hal_charger_oplus)"),
        "expected original CIL content to be preserved"
    );
    assert!(
        rendered.contains("; BEGIN generated by sepolicy-inject-rs"),
        "expected generated patch header in rendered CIL"
    );
    assert!(rendered.contains("(type test_domain)"));
    assert!(rendered.contains("(roletype object_r test_domain)"));
    assert!(rendered.contains("(type test_exec)"));
    assert!(rendered.contains("(roletype object_r test_exec)"));
    assert!(rendered.contains("(typeattribute test_attr)"));
    assert!(rendered.contains("(expandtypeattribute (test_attr) false)"));
    assert!(rendered.contains("(typeattributeset domain (test_domain))"));
    assert!(rendered.contains("(typeattributeset exec_type (test_exec))"));
    assert!(rendered.contains("(typeattributeset file_type (test_exec))"));
    assert!(rendered.contains("(typeattributeset test_attr (test_domain))"));
    assert!(rendered.contains("(allow test_domain test_exec (file (open read)))"));
    assert!(rendered.contains("(typetransition init test_exec process test_domain)"));
    assert!(rendered.contains("(typepermissive test_domain)"));
}

#[test]
fn test_patch_cil_source_supports_project_te_macro_expansion() {
    let base_cil = fixture_path("extract_label.cil");
    let te_path = repo_path("policies/project.te");
    let out_file = TempPath::new("cil");

    let macros = [
        fixture_path("global_macros.m4"),
        fixture_path("te_macros.m4"),
        fixture_path("self_domain_macros.m4"),
    ];

    let mut policy = CilSourcePolicy::from_file(&base_cil).unwrap_or_else(|e| {
        panic!(
            "failed to load base CIL fixture {}: {}",
            base_cil.display(),
            e
        )
    });

    policy
        .load_rules_from_file(&te_path, macros.iter())
        .unwrap_or_else(|e| {
            panic!(
                "failed to render CIL patch from {}: {}",
                te_path.display(),
                e
            )
        });

    policy.write(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to write patched CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    let rendered = fs::read_to_string(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to read rendered CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    assert!(
        rendered.contains("(type hal_project_oplus_aidl)"),
        "expected rendered CIL to declare the project HAL domain"
    );
    assert!(rendered.contains("(roletype object_r hal_project_oplus_aidl)"));
    assert!(rendered.contains("(type hal_project_oplus_aidl_exec)"));
    assert!(rendered.contains("(type hal_project_aidl_service)"));
    assert!(rendered.contains("(typeattribute hal_project_aidl)"));
    assert!(rendered.contains("(expandtypeattribute (hal_project_aidl) true)"));
    assert!(rendered.contains("(typeattribute hal_project_aidl_client)"));
    assert!(rendered.contains("(expandtypeattribute (hal_project_aidl_client) true)"));
    assert!(rendered.contains("(typeattribute hal_project_aidl_server)"));
    assert!(rendered.contains("(expandtypeattribute (hal_project_aidl_server) false)"));
    assert!(
        rendered.contains("(typeattributeset hal_project_aidl_server (hal_project_oplus_aidl))")
    );
    assert!(rendered.contains("(typeattributeset hal_project_aidl (hal_project_oplus_aidl))"));
    assert!(rendered.contains("(typeattributeset hal_project_aidl_client (bluetooth))"));
    assert!(rendered.contains("(typeattributeset hal_project_aidl_client (system_server))"));
    assert!(rendered.contains(
        "(typetransition init hal_project_oplus_aidl_exec process hal_project_oplus_aidl)"
    ));
    assert!(rendered.contains("(allow init hal_project_oplus_aidl_exec (file"));
    assert!(
        rendered.contains("(allow hal_project_oplus_aidl servicemanager (binder (call transfer)))")
    );
    assert!(
        rendered.contains("(allow servicemanager hal_project_oplus_aidl (binder (call transfer)))")
    );
    assert!(rendered.contains(
        "(allow hal_project_aidl_client hal_project_aidl_service (service_manager (find)))"
    ));
    assert!(rendered.contains(
        "(allow hal_project_aidl_server hal_project_aidl_service (service_manager (add find)))"
    ));
    assert!(
        rendered.contains("(typeattribute base_typeattr_"),
        "expected Android-style helper attributes for negative or compound TE sets"
    );
    assert!(
        rendered.contains("(typeattributeset base_typeattr_"),
        "expected Android-style helper typeattributesets for synthesized CIL set expressions"
    );
    assert!(
        rendered.contains("(neverallow base_typeattr_"),
        "expected rendered neverallow rules from Android HAL macros"
    );
    assert!(
        rendered.contains(
            "(allow hal_project_oplus_aidl hal_project_oplus_aidl (file (getattr ioctl lock map open read watch watch_reads)))"
        ),
        "expected file-class self-access to be emitted as its own CIL allow rule"
    );
    assert!(
        rendered.contains(
            "(allow hal_project_oplus_aidl hal_project_oplus_aidl (lnk_file (getattr ioctl lock map open read watch watch_reads)))"
        ),
        "expected lnk_file self-access to be emitted as its own CIL allow rule"
    );
    assert!(
        !rendered.contains(
            "(allow hal_project_oplus_aidl hal_project_oplus_aidl (file (getattr ioctl lock map open read watch watch_reads)) (lnk_file"
        ),
        "expected no multi-class allow rule to be emitted for file and lnk_file together"
    );
}

#[test]
fn test_patch_cil_source_uses_android_base_typeattr_naming_and_continues_vendor_counter() {
    let base_cil = repo_path("vendor_sepolicy.cil");
    let te_path = repo_path("policies/project.te");
    let out_file = TempPath::new("cil");

    let macros = [
        fixture_path("global_macros.m4"),
        fixture_path("te_macros.m4"),
        fixture_path("self_domain_macros.m4"),
    ];

    let mut policy = CilSourcePolicy::from_file(&base_cil).unwrap_or_else(|e| {
        panic!(
            "failed to load vendor CIL fixture {}: {}",
            base_cil.display(),
            e
        )
    });

    policy
        .load_rules_from_file(&te_path, macros.iter())
        .unwrap_or_else(|e| {
            panic!(
                "failed to render vendor CIL patch from {}: {}",
                te_path.display(),
                e
            )
        });

    policy.write(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to write patched vendor CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    let rendered = fs::read_to_string(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to read rendered vendor CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    assert!(
        !rendered.contains("spinject_internal_attr_"),
        "legacy helper attribute names should not appear in rendered vendor CIL"
    );
    assert!(
        rendered.contains("(typeattribute base_typeattr_719_32_0)"),
        "expected helper attribute numbering to continue from the highest vendor base_typeattr_* symbol"
    );
    assert!(
        rendered.contains("(typeattributeset base_typeattr_719_32_0"),
        "expected the first generated vendor helper attribute to use Android base_typeattr naming"
    );
    assert!(
        rendered.contains("(neverallow base_typeattr_719_32_0"),
        "expected rendered neverallow rules to reference Android-style helper attributes"
    );
    assert!(
        !rendered.contains("(allow init_32_0 hal_project_oplus_aidl_exec (file"),
        "expected no implicit Android symbol remapping without explicit mapping files"
    );
    assert!(
        rendered.contains("(allow init hal_project_oplus_aidl_exec (file"),
        "expected unsuffixed TE names to remain unsuffixed without explicit mapping files"
    );
}

#[test]
fn test_patch_cil_source_uses_explicit_mapping_files_for_android_versioned_symbols() {
    let base_cil = fixture_path("extract_label.cil");
    let mapping_file = TempPath::new("cil");
    let te_path = repo_path("policies/project.te");
    let out_file = TempPath::new("cil");

    fs::write(
        mapping_file.path(),
        r#"
(typeattributeset init_32_0 (init))
(typeattributeset servicemanager_32_0 (servicemanager))
(typeattributeset block_device_32_0 (block_device))
(typeattributeset sysfs_32_0 (sysfs sysfs_mem_sleep sysfs_udc))
(typeattributeset bluetooth_32_0 (bluetooth))
(typeattributeset system_server_32_0 (system_server))
"#,
    )
    .unwrap_or_else(|e| {
        panic!(
            "failed to write temporary mapping CIL file {}: {}",
            mapping_file.path().display(),
            e
        )
    });

    let macros = [
        fixture_path("global_macros.m4"),
        fixture_path("te_macros.m4"),
        fixture_path("self_domain_macros.m4"),
    ];

    let mut policy = CilSourcePolicy::from_file(&base_cil).unwrap_or_else(|e| {
        panic!(
            "failed to load base CIL fixture {}: {}",
            base_cil.display(),
            e
        )
    });

    policy
        .load_mapping_files([mapping_file.path()])
        .unwrap_or_else(|e| {
            panic!(
                "failed to load mapping CIL file {}: {}",
                mapping_file.path().display(),
                e
            )
        });

    policy
        .load_rules_from_file(&te_path, macros.iter())
        .unwrap_or_else(|e| {
            panic!(
                "failed to render mapped CIL patch from {}: {}",
                te_path.display(),
                e
            )
        });

    policy.write(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to write patched mapped CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    let rendered = fs::read_to_string(out_file.path()).unwrap_or_else(|e| {
        panic!(
            "failed to read rendered mapped CIL fixture {}: {}",
            out_file.path().display(),
            e
        )
    });

    assert!(
        rendered.contains("(allow init_32_0 hal_project_oplus_aidl_exec (file"),
        "expected init to resolve through explicit mapping files"
    );
    assert!(
        rendered.contains("(allow init_32_0 hal_project_oplus_aidl (process (transition)))"),
        "expected init process transition rule to use the mapped versioned symbol"
    );
    assert!(rendered.contains(
        "(typetransition init_32_0 hal_project_oplus_aidl_exec process hal_project_oplus_aidl)"
    ));
    assert!(
        rendered.contains(
            "(allow hal_project_oplus_aidl servicemanager_32_0 (binder (call transfer)))"
        ),
        "expected servicemanager to resolve through explicit mapping files"
    );
    assert!(
        rendered.contains(
            "(allow servicemanager_32_0 hal_project_oplus_aidl (binder (call transfer)))"
        ),
        "expected servicemanager reply binder rule to use the mapped versioned symbol"
    );
    assert!(
        rendered.contains("(allow hal_project_oplus_aidl block_device_32_0 (dir"),
        "expected block_device to resolve through explicit mapping files"
    );
    assert!(
        rendered.contains(
            "(allow hal_project_oplus_aidl block_device_32_0 (file (getattr ioctl lock map open read watch watch_reads)))"
        ),
        "expected block_device file-class access to be emitted as its own CIL allow rule"
    );
    assert!(
        rendered.contains(
            "(allow hal_project_oplus_aidl block_device_32_0 (lnk_file (getattr ioctl lock map open read watch watch_reads)))"
        ),
        "expected block_device lnk_file access to be emitted as its own CIL allow rule"
    );
    assert!(
        !rendered.contains(
            "(allow hal_project_oplus_aidl block_device_32_0 (file (getattr ioctl lock map open read watch watch_reads)) (lnk_file"
        ),
        "expected no combined multi-class block_device allow rule in generated CIL"
    );
    assert!(
        rendered.contains(
            "(allow hal_project_oplus_aidl sysfs_32_0 (file (append getattr ioctl lock map open read watch watch_reads write)))"
        ),
        "expected flat multi-name sysfs mapping to resolve sysfs to sysfs_32_0"
    );
    assert!(
        !rendered.contains(
            "(allow hal_project_oplus_aidl sysfs (file (append getattr ioctl lock map open read watch watch_reads write)))"
        ),
        "expected no unsuffixed sysfs allow rule after applying the flat multi-name mapping"
    );
    assert!(
        rendered.contains("(typeattributeset hal_project_aidl_client (bluetooth_32_0))"),
        "expected bluetooth client membership to use the mapped versioned symbol"
    );
    assert!(
        rendered.contains("(typeattributeset hal_project_aidl_client (system_server_32_0))"),
        "expected system_server client membership to use the mapped versioned symbol"
    );
}
